### ISSUE TITLE
配置后无法打开测试页面并导致整个halo崩溃

### ISSUE THREAD

**Issue by MDQ0512** [pannanxu/halo-plugin-email#2]
配置后无法打开测试页面一直在加载，加载的过程中后台会卡死，无法进入其他页面，同时前端也无法打开
然后页面会有504提示，只能重启docker容器才能解决

**Comment by pannanxu** [comment]
尝试更新到 1.1.0 版本

**Comment by pannanxu** [comment]
目前已更新到1.1.0版本，请更新到最新版本后尝试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pannanxu/halo-plugin-email"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月17日(星期六) 凌晨1:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pannanxu/halo-plugin-email] 配置后无法打开测试页面并导致整个halo崩溃 (Issue #2)





 
配置后无法打开测试页面一直在加载，加载的过程中后台会卡死，无法进入其他页面，同时前端也无法打开
 然后页面会有504提示，只能重启docker容器才能解决

**Comment by MDQ0512** [comment]
配置成功了，感谢帮助

**Comment by MDQ0512** [comment]
不过在配置中，发现一个问题
如果选择smtp协议并且也开启了tls，那么测试将显示失败，
如果选择smtps协议并开启tls，测试才会成功，
不知道这是邮件服务商的问题还是插件的问题

**Comment by pannanxu** [comment]
> 不过在配置中，发现一个问题 如果选择smtp协议并且也开启了tls，那么测试将显示失败， 如果选择smtps协议并开启tls，测试才会成功， 不知道这是邮件服务商的问题还是插件的问题

请问配置的端口是什么？

- 465端口一般是smtps协议的
- 587端口是startls。我测试采用QQ邮箱服务器使用此端口和smtp协议是可以的

**Comment by MDQ0512** [comment]
使用的是465端口，腾讯企业邮箱
刚刚去看了下，需要使用ssl，所以只能用smtps
