### ISSUE TITLE
关闭新评论审核后的评论无邮件提醒

### ISSUE THREAD

**Issue by MDQ0512** [pannanxu/halo-plugin-email#3]
关闭新评论审核后的评论无邮件提醒

**Comment by pannanxu** [comment]
目前推送的策略是：如果开启了评论审核，则会通过插件配置的 `管理员邮箱` 进行推送。

如果关闭了评论审核，则会通知文章的创建人，推送邮箱可以在 `编辑用户` 界面找到 `常规 -> 电子邮箱` 

如果文章创建人与评论人的邮件相同，则不会给文章创建人推送通知

如果回复创建人回复的评论的创建人邮件相同，则不会给评论的创建人推送

> 关闭新评论审核后的评论无邮件提醒

**Comment by MDQ0512** [comment]
好的，了解了

**Comment by sun0225SUN** [comment]
> 目前推送的策略是：如果开启了评论审核，则会通过插件配置的 `管理员邮箱` 进行推送。
> 
> 如果关闭了评论审核，则会通知文章的创建人，推送邮箱可以在 `编辑用户` 界面找到 `常规 -> 电子邮箱`
> 
> 如果文章创建人与评论人的邮件相同，则不会给文章创建人推送通知
> 
> 如果回复创建人回复的评论的创建人邮件相同，则不会给评论的创建人推送
> 
> > 关闭新评论审核后的评论无邮件提醒

建议将目前的推送策略在`readme.md`中注明:rocket:
