### ISSUE TITLE
插件中的“邮箱配置管理”无反应

### ISSUE THREAD

**Issue by Almost42** [pannanxu/halo-plugin-email#4]
路径：插件设置-权限模板-Email Config-邮箱配置管理
问题：点击该按钮无反应

**Comment by MDQ0512** [comment]
看详情后的`基本设置`

**Comment by pannanxu** [comment]
权限配置可以考虑去除的，只需要管理员拥有配置权限即可。

如果需要设置邮件服务器的配置可以参考 @MDQ0512 所说：进入 `基本配置` 的tab

> 路径：插件设置-权限模板-Email Config-邮箱配置管理 问题：点击该按钮无反应
