### ISSUE TITLE
测试接口返回true，但未收到邮件通知

### ISSUE THREAD

**Issue by sun0225SUN** [pannanxu/halo-plugin-email#5]
![image](https://user-images.githubusercontent.com/79169717/211014030-1a765a8c-3f12-49a1-b8ff-322c247c34c9.png)

上次（1.5号）测试正常，今天收到一条评论，发现未给我发邮件，配置项设置的应该没问题，不清楚问题所在。。。

**Comment by pannanxu** [comment]
看看这条问题是否能够帮助到您 #3 

或者尝试更新最新版本

**Comment by sun0225SUN** [comment]
> 看看这条问题是否能够帮助到您 #3
> 
> 或者尝试更新最新版本

好的

**Comment by sun0225SUN** [comment]
感谢，经测试，通知已经正常了

![image](https://user-images.githubusercontent.com/79169717/211188160-2aca6277-c861-456a-b16a-ad4daefdc5d9.png)
