### ISSUE TITLE
不兼容halo2.2.0

### ISSUE THREAD

**Issue by MDQ0512** [pannanxu/halo-plugin-email#6]
不兼容halo2.2.0，升级后无法启用，卸载后重新安装也无法启用，提示undefined
![image](https://user-images.githubusercontent.com/57866775/215975989-81faab32-b6f2-4c79-a72b-324709d97d57.png)

**Comment by li-guohao** [comment]
+1

**Comment by AirboZH** [comment]
+1

**Comment by Anonymous-Vhacker** [comment]
+1

**Comment by CnDaiL** [comment]
+1

**Comment by pannanxu** [comment]
> 不兼容halo2.2.0，升级后无法启用，卸载后重新安装也无法启用，提示undefined ![image](https://user-images.githubusercontent.com/57866775/215975989-81faab32-b6f2-4c79-a72b-324709d97d57.png)

请尝试更新到最新版本
@li-guohao @AirboZH @CnDaiL @Anonymous-Vhacker @MDQ0512

**Comment by CnDaiL** [comment]
大佬，我更新了以后，无法保存，然后测试一直是 无法访问 

我觉得我都填写对了参数了呀

**Comment by pannanxu** [comment]
> 大佬，我更新了以后，无法保存，然后测试一直是 无法访问
> 
> 我觉得我都填写对了参数了呀

https://github.com/pannanxu/halo-plugin-email/releases/tag/halo-2.2.x

再次尝试下载这个版本。

**Comment by CnDaiL** [comment]
> > 大佬，我更新了以后，无法保存，然后测试一直是 无法访问
> > 我觉得我都填写对了参数了呀
> 
> https://github.com/pannanxu/halo-plugin-email/releases/tag/halo-2.2.x
> 
> 再次尝试下载这个版本。

http://IP:port/apis/io.mvvm.halo.plugins.email/testConnection

里边的ip是我服务器的IP吧？ port 是在插件里设置的那个 端口数字吧？
然后邮件服务器的密码。非邮件的登陆密码.  这个是我给邮箱那边发短信，授权开的一堆jaslfjdasklfajkdf这个类似的密码吧？

保存了，然后 测试，就是一直无法访问网站。

**Comment by CnDaiL** [comment]
> 

经过大佬 @AirboZH  的指点，终于成功了！ 感谢作者更新，辛苦！
