### ISSUE TITLE
每次重新启动halo都需要重新请求一次api才能正常使用

### ISSUE THREAD

**Issue by AuroraStarry** [pannanxu/halo-plugin-email#8]
每次重新启动halo都需要重新请求一次`/apis/io.mvvm.halo.plugins.email/testConnection`才能正常使用

**Comment by pannanxu** [comment]
> 每次重新启动halo都需要重新请求一次`/apis/io.mvvm.halo.plugins.email/testConnection`才能正常使用

目前的设计是这样，后续可以考虑插件启动时进行一次测试连接
